package main

import (
	"fmt"
)
func main(){
	//set the total to zero
	total := 0
	//i and x set to first numbers of Fibonacci sequence
	i := 1
	x := 1
	var temp int
	for i < 4000001 {
		//first round temp = 1
		temp = x
		// x =2
		x = x + i
		//i == 1
		i = temp
		// i is the numbers in the Fibonacci sequence. Now check if i is even, if it is even, add it to the total
		if(i%2 == 0){
			total += i;
		}

	}
	//print the total
	fmt.Println(total)
}

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.